#include <bits/stdc++.h>

#include "basics.hpp"
#include "int128.hpp"
#include "numtheo/dis_log.hpp"
#include "numtheo/euler_sieve.hpp"
#include "numtheo/excrt.hpp"
#include "numtheo/fast_dis_ln.hpp"
#include "numtheo/modint.hpp"
#include "numtheo/mul_inv.hpp"
#include "numtheo/o1gcd.hpp"
#include "numtheo/pollard_rho.hpp"
#include "numtheo/prim_root.hpp"
#include "numtheo/prod_funcs.hpp"
#include "numtheo/quad_res.hpp"